import AppKit
import AVFoundation
import Vision

final class ScannerService:BaseService,AVCaptureVideoDataOutputSampleBufferDelegate{
    private var session:AVCaptureSession?;private var layer:AVCaptureVideoPreviewLayer?;private var overlay:NSView?;private var scanCallback:Callback?;private var once=false;private var onShow:Callback?;private var onHide:Callback?;private var isProcessingFrame=false
    override func exec(action:String,args:[Any],callback:Callback){switch action{case"show":show(args,callback);case"hide":hide(callback);case"scan":once=(args.first as? Bool)==true;scanCallback=callback;case"update":update(args,callback);case"setTheme":callback.success();case"setOnShowListener":onShow=callback;callback.success(nil,keep:true);case"setOnHideListener":onHide=callback;callback.success(nil,keep:true);default:callback.error("Unknown action")}}
    private func show(_ args:[Any],_ callback:Callback){let begin={DispatchQueue.main.async{guard let root=self.viewController?.view else{return callback.error("No window")};let d=args.first as? [String:Any] ?? [:];let frame=NSRect(x:d["x"] as? Double ?? 0,y:root.bounds.height-(d["y"] as? Double ?? 0)-(d["h"] as? Double ?? root.bounds.height),width:d["w"] as? Double ?? root.bounds.width,height:d["h"] as? Double ?? root.bounds.height);let v=NSView(frame:frame);v.wantsLayer=true;v.layer?.backgroundColor=NSColor.black.cgColor;root.addSubview(v);self.overlay=v;self.start(v,callback)}};switch AVCaptureDevice.authorizationStatus(for:.video){case.authorized:begin();case.notDetermined:AVCaptureDevice.requestAccess(for:.video){$0 ? begin():callback.error("Camera permission denied")};default:callback.error("Camera permission denied — enable it in System Settings")}}
    private func start(_ view:NSView,_ callback:Callback){guard let device=AVCaptureDevice.default(for:.video),let input=try? AVCaptureDeviceInput(device:device)else{return callback.error("No camera available")};let s=AVCaptureSession();guard s.canAddInput(input)else{return callback.error("Cannot use camera")};s.addInput(input);let out=AVCaptureVideoDataOutput();out.alwaysDiscardsLateVideoFrames=true;guard s.canAddOutput(out)else{return callback.error("Cannot scan QR codes")};s.addOutput(out);out.setSampleBufferDelegate(self,queue:DispatchQueue(label:"shellular.scanner.vision",qos:.userInitiated));let l=AVCaptureVideoPreviewLayer(session:s);l.frame=view.bounds;l.autoresizingMask=[.layerWidthSizable,.layerHeightSizable];l.videoGravity = .resizeAspectFill;view.layer?.addSublayer(l);session=s;layer=l;DispatchQueue.global(qos:.userInitiated).async{s.startRunning();DispatchQueue.main.async{callback.success();self.onShow?.success(nil,keep:true)}}}
    private func update(_ args:[Any],_ callback:Callback){guard let v=overlay,let root=viewController?.view,let d=args.first as? [String:Any]else{return callback.error("No scanner")};DispatchQueue.main.async{v.frame=NSRect(x:d["x"] as? Double ?? 0,y:root.bounds.height-(d["y"] as? Double ?? 0)-(d["h"] as? Double ?? 0),width:d["w"] as? Double ?? 0,height:d["h"] as? Double ?? 0);self.layer?.frame=v.bounds;callback.success()}}
    private func hide(_ callback:Callback){session?.stopRunning();session=nil;layer?.removeFromSuperlayer();layer=nil;overlay?.removeFromSuperview();overlay=nil;scanCallback=nil;isProcessingFrame=false;callback.success();onHide?.success(nil,keep:true)}
    func captureOutput(_ output:AVCaptureOutput,didOutput sampleBuffer:CMSampleBuffer,from connection:AVCaptureConnection){guard scanCallback != nil,!isProcessingFrame,let buffer=CMSampleBufferGetImageBuffer(sampleBuffer)else{return};isProcessingFrame=true;let request=VNDetectBarcodesRequest{[weak self] request,_ in guard let self else{return};defer{self.isProcessingFrame=false};let values=(request.results as? [VNBarcodeObservation])?.filter{$0.symbology == .qr}.compactMap(\.payloadStringValue) ?? [];guard !values.isEmpty else{return};let results=values.map{["rawValue":$0,"displayValue":$0,"format":"256","valueType":"0"]};DispatchQueue.main.async{self.scanCallback?.success(results,keep:!self.once);if self.once{self.scanCallback=nil;self.hide(Callback(id:-1,webView:nil))}}};request.symbologies=[.qr];try? VNImageRequestHandler(cvPixelBuffer:buffer,orientation:.up).perform([request])}
}
