import type Theme from "classes/theme";
import type { editor } from "monaco-editor";
import {
	monacoTokenColor,
	normalizeMonacoColor,
	withMonacoAlpha,
} from "./monacoColor";

export function monacoThemeName(theme: Theme) {
	return `shellular-${theme.name.toLowerCase()}`;
}

export function createMonacoTheme(theme: Theme): editor.IStandaloneThemeData {
	const dark = theme.type !== "light";
	const terminal = theme.xtermTheme;
	const accentSelection = withMonacoAlpha(theme.accent, dark ? 0.24 : 0.2);
	const accentSelectionInactive = withMonacoAlpha(
		theme.accent,
		dark ? 0.12 : 0.1,
	);
	const colors: Record<string, string> = {
		"editor.background": theme.primary,
		"editor.foreground": theme.primaryText,
		"editorLineNumber.foreground": theme.textMuted,
		"editorLineNumber.activeForeground": theme.primaryText,
		"editorCursor.foreground": theme.accent,
		"editor.selectionBackground": accentSelection,
		"editor.inactiveSelectionBackground": accentSelectionInactive,
		"editor.selectionHighlightBackground": withMonacoAlpha(theme.accent, 0.1),
		"editor.wordHighlightBackground": withMonacoAlpha(theme.info, 0.12),
		"editor.wordHighlightStrongBackground": withMonacoAlpha(theme.accent, 0.16),
		"editor.findMatchBackground": withMonacoAlpha(theme.accent, 0.34),
		"editor.findMatchHighlightBackground": withMonacoAlpha(theme.accent, 0.16),
		"editor.lineHighlightBackground": theme.surfaceSoft,
		"editor.lineHighlightBorder": "transparent",
		"editorGutter.background": theme.primary,
		"editorGutter.foldingControlForeground": theme.textMuted,
		"editorGutter.addedBackground": theme.success,
		"editorGutter.modifiedBackground": theme.info,
		"editorGutter.deletedBackground": theme.danger,
		"editorIndentGuide.background1": theme.lineSoft,
		"editorIndentGuide.activeBackground1": withMonacoAlpha(theme.accent, 0.44),
		"editorWhitespace.foreground": withMonacoAlpha(theme.textMuted, 0.24),
		"editorBracketMatch.background": withMonacoAlpha(theme.accent, 0.12),
		"editorBracketMatch.border": withMonacoAlpha(theme.accent, 0.58),
		"editorBracketHighlight.foreground1": terminal.cyan ?? theme.info,
		"editorBracketHighlight.foreground2": terminal.yellow ?? theme.accent,
		"editorBracketHighlight.foreground3": terminal.magenta ?? theme.accent2,
		"editorBracketHighlight.foreground4": terminal.blue ?? theme.info,
		"editorBracketHighlight.foreground5": terminal.green ?? theme.success,
		"editorBracketHighlight.foreground6": terminal.brightCyan ?? theme.accent,
		"editorBracketHighlight.unexpectedBracketForeground": theme.danger,
		"editorStickyScroll.background": theme.primary,
		"editorStickyScrollHover.background": theme.surfaceSoft,
		"editorStickyScroll.border": theme.lineSoft,
		"editorStickyScroll.shadow": "transparent",
		"minimap.background": theme.primary,
		"minimap.selectionHighlight": withMonacoAlpha(theme.accent, 0.32),
		"minimap.findMatchHighlight": withMonacoAlpha(theme.accent, 0.46),
		"minimap.errorHighlight": theme.danger,
		"minimap.warningHighlight": theme.warning,
		"minimapSlider.background": theme.scrollbarThumb,
		"minimapSlider.hoverBackground": theme.scrollbarThumbHover,
		"minimapSlider.activeBackground": theme.scrollbarThumbActive,
		"editorOverviewRuler.background": theme.primary,
		"editorOverviewRuler.border": theme.lineSoft,
		"editorWidget.background": theme.popupBackground,
		"editorWidget.foreground": theme.popupText,
		"editorWidget.border": theme.popupBorderColor,
		"editorHoverWidget.background": theme.popupBackground,
		"editorHoverWidget.foreground": theme.popupText,
		"editorHoverWidget.border": theme.popupBorderColor,
		"editorHoverWidget.statusBarBackground": theme.surfaceStrong,
		"editorSuggestWidget.background": theme.popupBackground,
		"editorSuggestWidget.border": theme.popupBorderColor,
		"editorSuggestWidget.foreground": theme.popupText,
		"editorSuggestWidget.selectedBackground": theme.popupActiveBackground,
		"editorSuggestWidget.selectedForeground": theme.popupActiveText,
		"editorSuggestWidget.highlightForeground": theme.accent,
		"editorSuggestWidget.focusHighlightForeground": theme.accent,
		"input.background": theme.input,
		"input.foreground": theme.inputText,
		"input.border": theme.cardBorder,
		"input.placeholderForeground": theme.inputPlaceholder,
		"inputOption.activeBackground": withMonacoAlpha(theme.accent, 0.14),
		"inputOption.activeBorder": theme.accent,
		"inputOption.activeForeground": theme.primaryText,
		"inputValidation.errorBackground": withMonacoAlpha(theme.danger, 0.1),
		"inputValidation.errorBorder": theme.danger,
		"inputValidation.warningBackground": withMonacoAlpha(theme.warning, 0.1),
		"inputValidation.warningBorder": theme.warning,
		focusBorder: theme.accent,
		foreground: theme.primaryText,
		"list.activeSelectionBackground": theme.popupActiveBackground,
		"list.activeSelectionForeground": theme.popupActiveText,
		"list.inactiveSelectionBackground": theme.surfaceSoft,
		"list.inactiveSelectionForeground": theme.primaryText,
		"list.hoverBackground": theme.popupHoverBackground,
		"list.hoverForeground": theme.popupHoverText,
		"list.focusBackground": theme.popupActiveBackground,
		"list.focusForeground": theme.popupActiveText,
		"menu.background": theme.popupBackground,
		"menu.foreground": theme.popupText,
		"menu.selectionBackground": theme.popupActiveBackground,
		"menu.selectionForeground": theme.popupActiveText,
		"menu.border": theme.popupBorderColor,
		"menu.separatorBackground": theme.lineSoft,
		"quickInput.background": theme.popupBackground,
		"quickInput.foreground": theme.popupText,
		"quickInputList.focusBackground": theme.popupActiveBackground,
		"quickInputList.focusForeground": theme.popupActiveText,
		"quickInputList.focusIconForeground": theme.accent,
		"pickerGroup.border": theme.lineSoft,
		"pickerGroup.foreground": theme.accent,
		"breadcrumb.background": theme.primary,
		"breadcrumb.foreground": theme.textMuted,
		"breadcrumb.focusForeground": theme.primaryText,
		"breadcrumb.activeSelectionForeground": theme.accent,
		"breadcrumbPicker.background": theme.popupBackground,
		"scrollbar.shadow": "transparent",
		"scrollbarSlider.background": theme.scrollbarThumb,
		"scrollbarSlider.hoverBackground": theme.scrollbarThumbHover,
		"scrollbarSlider.activeBackground": theme.scrollbarThumbActive,
		"diffEditor.insertedLineBackground": withMonacoAlpha(theme.success, 0.12),
		"diffEditor.removedLineBackground": withMonacoAlpha(theme.danger, 0.14),
		"diffEditor.insertedTextBackground": withMonacoAlpha(theme.success, 0.24),
		"diffEditor.removedTextBackground": withMonacoAlpha(theme.danger, 0.26),
		"diffEditorGutter.insertedLineBackground": withMonacoAlpha(
			theme.success,
			0.2,
		),
		"diffEditorGutter.removedLineBackground": withMonacoAlpha(
			theme.danger,
			0.22,
		),
		"diffEditorOverview.insertedForeground": withMonacoAlpha(
			theme.success,
			0.68,
		),
		"diffEditorOverview.removedForeground": withMonacoAlpha(theme.danger, 0.68),
		"diffEditor.diagonalFill": theme.lineSoft,
	};
	return {
		base: dark ? "vs-dark" : "vs",
		inherit: true,
		rules: [
			{
				token: "comment",
				foreground: monacoTokenColor(theme.textMuted),
				fontStyle: "italic",
			},
			{ token: "keyword", foreground: monacoTokenColor(theme.accent) },
			{
				token: "string",
				foreground: monacoTokenColor(terminal.green, theme.success),
			},
			{
				token: "number",
				foreground: monacoTokenColor(terminal.blue, theme.info),
			},
			{
				token: "type",
				foreground: monacoTokenColor(terminal.brightYellow, theme.accent),
			},
			{
				token: "type.identifier",
				foreground: monacoTokenColor(terminal.brightYellow, theme.accent),
			},
			{
				token: "function",
				foreground: monacoTokenColor(terminal.brightBlue, theme.info),
			},
			{
				token: "variable",
				foreground: monacoTokenColor(theme.primaryText),
			},
			{
				token: "identifier",
				foreground: monacoTokenColor(theme.primaryText),
			},
			{
				token: "delimiter",
				foreground: monacoTokenColor(theme.textMuted),
			},
			{
				token: "tag",
				foreground: monacoTokenColor(theme.accent),
			},
			{
				token: "attribute.name",
				foreground: monacoTokenColor(terminal.cyan, theme.info),
			},
			{
				token: "regexp",
				foreground: monacoTokenColor(terminal.cyan, theme.info),
			},
			{
				token: "invalid",
				foreground: monacoTokenColor(theme.danger),
				fontStyle: "underline",
			},
		],
		colors: Object.fromEntries(
			Object.entries(colors).map(([name, value]) => [
				name,
				normalizeMonacoColor(value),
			]),
		),
	};
}
