import type Theme from "classes/theme";
import type { editor } from "monaco-editor";
import { toThemeId } from "themes/id";
import {
	monacoTokenColor,
	normalizeMonacoColor,
	withColorAlpha,
} from "./monacoColor";

export function monacoThemeName(theme: Theme) {
	return `shellular-${toThemeId(theme.name)}`;
}

export function createMonacoTheme(theme: Theme): editor.IStandaloneThemeData {
	const dark = theme.type !== "light";
	const syntax = theme.syntaxTheme;
	const accentSelection = withColorAlpha(theme.accent, dark ? 0.24 : 0.2);
	const accentSelectionInactive = withColorAlpha(
		theme.accent,
		dark ? 0.12 : 0.1,
	);
	const colors: Record<string, string> = {
		"editor.background": theme.primary,
		"editor.foreground": theme.primaryText,
		"editorLineNumber.foreground": theme.textMuted,
		"editorLineNumber.activeForeground": theme.primaryText,
		"editorCursor.foreground": theme.accent,
		"editor.selectionBackground": accentSelection,
		"editor.inactiveSelectionBackground": accentSelectionInactive,
		"editor.selectionHighlightBackground": withColorAlpha(theme.accent, 0.1),
		"editor.wordHighlightBackground": withColorAlpha(theme.info, 0.12),
		"editor.wordHighlightStrongBackground": withColorAlpha(theme.accent, 0.16),
		"editor.findMatchBackground": withColorAlpha(theme.accent, 0.34),
		"editor.findMatchHighlightBackground": withColorAlpha(theme.accent, 0.16),
		"editor.lineHighlightBackground": theme.surfaceSoft,
		"editor.lineHighlightBorder": "transparent",
		"editorGutter.background": theme.primary,
		"editorGutter.foldingControlForeground": theme.textMuted,
		"editorGutter.addedBackground": theme.success,
		"editorGutter.modifiedBackground": theme.info,
		"editorGutter.deletedBackground": theme.danger,
		"editorIndentGuide.background1": theme.lineSoft,
		"editorIndentGuide.activeBackground1": withColorAlpha(theme.accent, 0.44),
		"editorWhitespace.foreground": withColorAlpha(theme.textMuted, 0.24),
		"editorBracketMatch.background": withColorAlpha(theme.accent, 0.12),
		"editorBracketMatch.border": withColorAlpha(theme.accent, 0.58),
		"editorBracketHighlight.foreground1": syntax.property,
		"editorBracketHighlight.foreground2": syntax.type,
		"editorBracketHighlight.foreground3": syntax.keyword,
		"editorBracketHighlight.foreground4": syntax.function,
		"editorBracketHighlight.foreground5": syntax.string,
		"editorBracketHighlight.foreground6": syntax.regexp,
		"editorBracketHighlight.unexpectedBracketForeground": theme.danger,
		"editorStickyScroll.background": theme.primary,
		"editorStickyScrollHover.background": theme.surfaceSoft,
		"editorStickyScroll.border": theme.lineSoft,
		"editorStickyScroll.shadow": "transparent",
		"minimap.background": theme.primary,
		"minimap.selectionHighlight": withColorAlpha(theme.accent, 0.32),
		"minimap.findMatchHighlight": withColorAlpha(theme.accent, 0.46),
		"minimap.errorHighlight": theme.danger,
		"minimap.warningHighlight": theme.warning,
		"minimapSlider.background": theme.scrollbarThumb,
		"minimapSlider.hoverBackground": theme.scrollbarThumbHover,
		"minimapSlider.activeBackground": theme.scrollbarThumbActive,
		"editorOverviewRuler.background": theme.primary,
		"editorOverviewRuler.border": theme.lineSoft,
		"editorWidget.background": theme.popupBackground,
		"editorWidget.foreground": theme.popupText,
		"editorWidget.border": theme.popupBorderColor,
		"editorHoverWidget.background": theme.popupBackground,
		"editorHoverWidget.foreground": theme.popupText,
		"editorHoverWidget.border": theme.popupBorderColor,
		"editorHoverWidget.statusBarBackground": theme.surfaceStrong,
		"editorSuggestWidget.background": theme.popupBackground,
		"editorSuggestWidget.border": theme.popupBorderColor,
		"editorSuggestWidget.foreground": theme.popupText,
		"editorSuggestWidget.selectedBackground": theme.popupActiveBackground,
		"editorSuggestWidget.selectedForeground": theme.popupActiveText,
		"editorSuggestWidget.highlightForeground": theme.accent,
		"editorSuggestWidget.focusHighlightForeground": theme.accent,
		"input.background": theme.input,
		"input.foreground": theme.inputText,
		"input.border": theme.cardBorder,
		"input.placeholderForeground": theme.inputPlaceholder,
		"inputOption.activeBackground": withColorAlpha(theme.accent, 0.14),
		"inputOption.activeBorder": theme.accent,
		"inputOption.activeForeground": theme.primaryText,
		"inputValidation.errorBackground": withColorAlpha(theme.danger, 0.1),
		"inputValidation.errorBorder": theme.danger,
		"inputValidation.warningBackground": withColorAlpha(theme.warning, 0.1),
		"inputValidation.warningBorder": theme.warning,
		focusBorder: theme.accent,
		foreground: theme.primaryText,
		"list.activeSelectionBackground": theme.popupActiveBackground,
		"list.activeSelectionForeground": theme.popupActiveText,
		"list.inactiveSelectionBackground": theme.surfaceSoft,
		"list.inactiveSelectionForeground": theme.primaryText,
		"list.hoverBackground": theme.popupHoverBackground,
		"list.hoverForeground": theme.popupHoverText,
		"list.focusBackground": theme.popupActiveBackground,
		"list.focusForeground": theme.popupActiveText,
		"menu.background": theme.popupBackground,
		"menu.foreground": theme.popupText,
		"menu.selectionBackground": theme.popupActiveBackground,
		"menu.selectionForeground": theme.popupActiveText,
		"menu.border": theme.popupBorderColor,
		"menu.separatorBackground": theme.lineSoft,
		"quickInput.background": theme.popupBackground,
		"quickInput.foreground": theme.popupText,
		"quickInputList.focusBackground": theme.popupActiveBackground,
		"quickInputList.focusForeground": theme.popupActiveText,
		"quickInputList.focusIconForeground": theme.accent,
		"pickerGroup.border": theme.lineSoft,
		"pickerGroup.foreground": theme.accent,
		"breadcrumb.background": theme.primary,
		"breadcrumb.foreground": theme.textMuted,
		"breadcrumb.focusForeground": theme.primaryText,
		"breadcrumb.activeSelectionForeground": theme.accent,
		"breadcrumbPicker.background": theme.popupBackground,
		"scrollbar.shadow": "transparent",
		"scrollbarSlider.background": theme.scrollbarThumb,
		"scrollbarSlider.hoverBackground": theme.scrollbarThumbHover,
		"scrollbarSlider.activeBackground": theme.scrollbarThumbActive,
		"diffEditor.insertedLineBackground": withColorAlpha(theme.success, 0.12),
		"diffEditor.removedLineBackground": withColorAlpha(theme.danger, 0.14),
		"diffEditor.insertedTextBackground": withColorAlpha(theme.success, 0.24),
		"diffEditor.removedTextBackground": withColorAlpha(theme.danger, 0.26),
		"diffEditorGutter.insertedLineBackground": withColorAlpha(
			theme.success,
			0.2,
		),
		"diffEditorGutter.removedLineBackground": withColorAlpha(
			theme.danger,
			0.22,
		),
		"diffEditorOverview.insertedForeground": withColorAlpha(
			theme.success,
			0.68,
		),
		"diffEditorOverview.removedForeground": withColorAlpha(theme.danger, 0.68),
		"diffEditor.diagonalFill": theme.lineSoft,
	};
	return {
		base: dark ? "vs-dark" : "vs",
		inherit: true,
		rules: [
			{
				token: "comment",
				foreground: monacoTokenColor(syntax.comment),
				fontStyle: "italic",
			},
			{ token: "keyword", foreground: monacoTokenColor(syntax.keyword) },
			{
				token: "string",
				foreground: monacoTokenColor(syntax.string),
			},
			{
				token: "number",
				foreground: monacoTokenColor(syntax.number),
			},
			{
				token: "type",
				foreground: monacoTokenColor(syntax.type),
			},
			{
				token: "type.identifier",
				foreground: monacoTokenColor(syntax.type),
			},
			{
				token: "function",
				foreground: monacoTokenColor(syntax.function),
			},
			{
				token: "variable",
				foreground: monacoTokenColor(syntax.variable),
			},
			{
				token: "identifier",
				foreground: monacoTokenColor(syntax.variable),
			},
			{
				token: "delimiter",
				foreground: monacoTokenColor(syntax.operator),
			},
			{
				token: "tag",
				foreground: monacoTokenColor(syntax.tag),
			},
			{
				token: "attribute.name",
				foreground: monacoTokenColor(syntax.property),
			},
			{
				token: "regexp",
				foreground: monacoTokenColor(syntax.regexp),
			},
			{
				token: "invalid",
				foreground: monacoTokenColor(theme.danger),
				fontStyle: "underline",
			},
		],
		colors: Object.fromEntries(
			Object.entries(colors).map(([name, value]) => [
				name,
				normalizeMonacoColor(value),
			]),
		),
	};
}
